### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by tk575** [myrafproject/myrafproject2#1]
Hello, I'm following the installation step by step but at the end when giving the command: "myraf2" the following message appears: "Can not  load MYRaf" . I'm using version 18.4.02 LTS of Ubuntu

**Comment by yucelkilic** [comment]
Dear @tk575,

Sorry for the issue. MYRaf version 2 is outdated for now. We are developing MYRaf v3 nowadays with python3 support. Please consider waiting for release three. I'll inform you when it is ready :)

Thank you for your understanding.
